version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sum-api
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_db_network
      
  adminer:
    image: adminer
    container_name: adminer_ui
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - my_db_network
volumes:
  db-data:


networks:
  my_db_network:
    driver: bridge